CREATE TYPE types AS ENUM (
  'water',
  'weight',
  'exercise'
);

CREATE TABLE log_entries (
  log_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER
    REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  log_type types NOT NULL,
  exercise_type TEXT,
  quanity DECIMAL,
  unit_of_measurement TEXT,
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ,
  calories DECIMAL
);