CREATE TYPE types AS ENUM (
  'water',
  'weight',
  'activity'
);

CREATE TABLE log_entries (
  log_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER
    REFERENCES users(user_id) ON DELETE CASCADE NOT NULL,
  log_type types NOT NULL,
  log_title TEXT,
  quanity DECIMAL,
  unit_of_meassurement TEXT,
  start_time TIMESTAMPTZ,
  end_time TIMESTAMPTZ,
  calories DECIMAL
);