CREATE TABLE water_entries (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT,
  quanit DECIMAL NOT NULL,
  unitOfMeasurement TEXT NOT NULL,
  date_time DATETIME NOT NULL,
  user_name TEXT
    REFERENCES users(user_name) ON DELETE CASCADE NOT NULL,
);