CREATE TABLE water_entry (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT,
  quanit NOT NULLy,
  unitOfMeasurement NOT NULL,
  date_time NOT NULL,
);

CREATE TABLE weight_entry (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT,
  quanity NOT NULL,
  unitOfMeasurement NOT NULL,
  date_time NOT NULL,
);

CREATE TABLE activity_entry (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT,
  activity_name NOT NULL,
  start_date_time NOT NULL,
  end_date_time NOT NULL,
  calories_burned ,
);