CREATE TABLE activity_entries (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT,
  activity_name TEXT NOT NULL,
  start_date_time DATETIME NOT NULL,
  end_date_time DATETIME NOT NULL,
  calories_burned DECIMAL,
  user_name TEXT
    REFERENCES users(user_name) ON DELETE CASCADE NOT NULL,
);